### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by davidkhala** [oracle/oracle-functions-samples#18]
Is this project actively maintained? Or any referral link to alternative sample projects?

**Comment by sachin-pikle** [comment]
Hi David, yes. This project is being actively maintained.

**Comment by davidkhala** [comment]
@sachin-pikle Nice to hear that. I wonder if we could consider merge of current auto-created PR by dependabot? range from #14 
 to #17

**Comment by sachin-pikle** [comment]
Yes, sorry for the delay. Will take care of this in the next couple of days.

**Comment by sachin-pikle** [comment]
Merged. Happy holidays!
