### ISSUE TITLE
Display an OCI Cloud Event - Tutorial not clear

### ISSUE THREAD

**Issue by pdadwal** [oracle/oracle-functions-samples#6]
Hello Team,
While following "Display an OCI Cloud Event" tutorial using Oracle functions in below tutorial , its not clear, how to test it.
https://github.com/oracle/oracle-functions-samples/blob/master/oci-event-display-python

Documentation simply refers to logs once Rule is created.

Please clarify, as I am unable to test it.

Thanks,
Pardeep

**Comment by sachin-pikle** [comment]
Thank you Pardeep for reporting this issue. I have made a minor change to the text. 

"You can create some resource such as an Object Storage bucket to generate an event."

**Comment by sachin-pikle** [comment]
Please check and confirm this addresses your issue.

**Comment by sachin-pikle** [comment]
Closing the issue. Please feel free to reopen, if the fix still doesn't address your issue.
